### PR TITLE
Add gradle support, cleanup

### PR DESCRIPTION
**Pull request by mvdan**
The submodules aren't used, so I don't know why they are there. I suppose they can be removed. Didn't do that in case you want them for something in the future.

### CODE REVIEW

**Comment by SamWhited** [comment]
What's the status of this PR? The repo appears to have been deleted, and I'm unable to get a reference to the commit (I had to download and apply the diff manually).

**Comment by mvdan** [comment]
Wow, this PR had been ignored for so long that I just forgot about it. I'll try to get the repo back up.

**Comment by mvdan** [comment]
Closing and opening a new one.

**Comment by mvdan** [comment]
Not opening a new one since PR 16 does a similar thing - although perhaps in a messier way. You can find an updated version of my changes in https://github.com/mvdan/NetCipher/tree/gradle

**Pull request closed without merging**
