### PR TITLE
new generic ProxyHelper interface and Psiphon3 implementation

### PR DESCRIPTION
**Pull request by n8fr8**
This implements a more generic, extensible way to discover and interact with local device proxies. Psiphon3 is the default implementation.

### CODE REVIEW

**Comment by eighthave** [comment]
I'm trying to make sense of the constants related to `Intent`s in *ProxyHelper.java*.  My guess is that having generic versions of `ACTION_STATUS` and `ACTION_START` is not going to be useful.  Instead, there should be versions of those constants for each type of proxy app, i.e. Orbot, Psiphon, etc. I think the app using NetCipher will always have to be aware of which proxy app it is using because they work too differently to be lumped together.

**Comment by n8fr8** [comment]
The use case was having an app be able to support different kinds of proxies through one standard set of Intent API code. With the SecureReader project, they have some logic that looks at what is installed and/or running and makes some sense of that to autoconfigure their proxying. Ultimately, to an app using NetCipher, it is just a local socks proxy, whether it be Tor, Psiphon, Meek, Obfs4 etc... it doesn't really work that different.

**Comment by eighthave** [comment]
Sure, the interface to the proxy part is the same, but the concept of "Start" and "Running" are quite different between them.  For example, Orbot requires a daemon to be running, other services do not.  If I understand Lantern correctly, it would be possible for NetCipher to support Lantern without even having an app installed since its just network settings, so "starting" just becomes configuring the right network settings.

So in the SecureReader case, `ProxyHelper` could provide a method to provide a list of installed proxy apps, then the app decides which to use, which it needs status from, and which it wants to start. Each proxy type therefore has their own status and start Intents, to keep them dead simple.  An app can then choose to send none, one or multiple and register for replies from the apps its interested in.

**Comment by n8fr8** [comment]
Psiphon has a daemon as well, and is basically very similar to Orbot, so in that case, what was needed was the same. I think we are still on the fence about how Meek, Obfs4 and other single-hop type obfuscating transports should work, but you are right that in the case of Lantern, it could be a very different set of scenarios.

Still, given that we have a finite known set of proxy types, then implementing specific intents and status for each isn't that much more work. I just think we need a "enable whatever proxy the user has that you know how to talk to, i don't really care which" type of interaction is something that should be supported.

**Comment by eighthave** [comment]
I think the "just get me online" interaction would be a NetCipher method, something like `startCircumventionProxy()` that would check for which apps are installed, then which are running, then have a default priority list, then send the correct start Intent based on that logic.  That keeps the Intent API really simple but flexible, since the Intents would be devoted to each app, but following the same pattern.

**Comment by eighthave** [comment]
Also, following the pattern of `OrbotHelper`, `ACTION_START` and `ACTION_STATUS` are Intents that are sent to the proxy app (i.e. Orbot), not sent to NetCipher.  The `ProxyHelper.ACTION_STATUS` is sent by NetCipher itself, when it should be sent from the Psiphon app.  Orbot is the app that sends `OrbotHelper.ACTION_STATUS`, for example.  If all the apps use the same `ACTION_STATUS` Intent action, then it will be difficult for the receiver to filter which app is sending a particular `ACTION_STATUS`.

**Comment by n8fr8** [comment]
Got it. Sounds good!

**Comment by eighthave** [comment]
Is Psiphon guaranteed to run on ports 1080 and 8080, or does it change its ports sometimes?  If so, then Psiphon will need to communcate that to NetCipher.  The current `PsiphonHelper` is written from the perspective as if it was code in Psiphon itself because it is broadcasting the proxy ports. But NetCipher represents the app's point of view when interacting with proxies like Orbot and Psiphon.

If those ports are fixed, then no need to broadcast those ports at all.  They can just be hard-coded into NetCipher, then used as the proxy whenever the app chooses to use Psiphon.

**Comment by vanevery** [comment]
They change, which is part of the difficulty of using Psiphon.
PsiphonHelper runs a port discovery routine which broadcasts the ports
making it easier to use.

**Comment by n8fr8** [comment]
We want Psiphon to adopt an Orbot style intent interface, but this was
our short term solution that does work.

**Pull request merged**
