### PR TITLE
Test updates and bump to android-23

### PR DESCRIPTION
**Pull request by eighthave**
This should hopefully get the tests running successfully in the travis-ci builds.  I also purged the old, unmaintained TLS Presense tests.  I think we can do all that those tests did in JUnit style tests using services like https://badssl.com

@commonsguy

### CODE REVIEW

**Comment by commonsguy** [comment]
By eyeball, this seems fine. Note that raising the `targetSdkVersion` to 23 means that you have to deal with runtime permissions, though I am not sure that there are any `dangerous` permissions floating about.

**Comment by eighthave** [comment]
Hmm, I think using netcipher only affects INTERNET permissions.  Would compiling with android-23 mean changes if this lib only needs INTERNET perms?  I thought that was automatic anyway.

**Comment by commonsguy** [comment]
> Would compiling with android-23 mean changes if this lib only needs INTERNET perms?

Nope, that's fine. `*_EXTERNAL_STORAGE` would be a problem, for example.

> I thought that was automatic anyway.

Insofar as the user isn't prompted about it from the Play Store, yes. You still need `<uses-permission>` for it, though.

**Comment by eighthave** [comment]
hmm, ok, I'm going to skip 23 now, since it also required `useLibrary 'org.apache.http.legacy'`

**Comment by commonsguy** [comment]
You weren't using the built-in HttpClient, I thought. I thought you were using `ch.boye`, which will exist regardless of `compileSdkVersion`. Perhaps my memory is fuzzy.

**Pull request merged**
