### PR TITLE
Mostly a SOCKS bug fix for Shawn

### PR DESCRIPTION
**Pull request by n8fr8**
SOCKS was incorrectly being used as HTTPHost scheme type, causing this bug:
https://dev.guardianproject.info/issues/5168

### CODE REVIEW

**Comment by vanevery** [comment]
Thanks n8fr8..  Solved my issues.   Who can do merge?

**Comment by n8fr8** [comment]
Hans will after review

**Comment by eighthave** [comment]
* why did you downgrade `project.properties` from `android-22` to `android-21`?

* commit e2db2e2db1c36923e47076d5f55f9970e51fc60d looks fine

* I don't know anything about the `WebView` stuff, so I just skimmed it to see if there was anything obvious.

**Comment by n8fr8** [comment]
>why did you downgrade project.properties from android-22 to android-21?

Didn't mean to do that. Will fix and update the PR.

>I don't know anything about the WebView stuff, so I just skimmed it to see if there was anything obvious.

This is what we are using in Orweb now, so it does work.

**Comment by eighthave** [comment]
Your new commit only partially restores it to `android-22`.  Can you just remove commits 3fb8f41 and 7fa9c1a and force push?  Its really easy to do, hit me up on IRC or IM.

**Pull request merged**
